name: Update CSS Files

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  update-css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Process CSS files
        run: python .github/scripts/process_css.py

      - name: Get last commit message for userstyle.css
        run: echo "LAST_COMMIT_MSG=$(git log -1 --pretty=%B -- userstyle.css)" >> $GITHUB_ENV

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add no-header.css neptune.css
          git commit -m "$LAST_COMMIT_MSG" || echo "No changes to commit"
          git push
